# Generated by Django 5.2.13 on 2026-04-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
