# Generated by Django 5.2.13 on 2026-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_action_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='area',
            field=models.CharField(default='Não informada', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='gap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strongest_point',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='weakest_point',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
