# Generated by Django 6.1 on 2026-08-18 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_area_assessment_gap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_interesse', models.CharField(max_length=255, verbose_name='Área ou Curso de Interesse')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo', to='assessments.perfil')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'db_table': 'objetivos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoIEP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iep_score', models.IntegerField(verbose_name='Índice de Evolução Pessoal')),
                ('diagnostic', models.CharField(max_length=255, verbose_name='Diagnóstico do IEP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objetivo_contexto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_iep', to='assessments.objetivo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_iep', to='assessments.perfil')),
            ],
            options={
                'verbose_name': 'Histórico do IEP',
                'verbose_name_plural': 'Históricos do IEP',
                'db_table': 'historicos_iep',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Competência')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nível da Competência (1 a 5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='assessments.perfil')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'db_table': 'competencias',
            },
        ),
    ]
