# Generated by Django 6.1 on 2026-08-19 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_perfil_objetivo_historicoiep_competencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicoiep',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={},
        ),
        migrations.RemoveField(
            model_name='historicoiep',
            name='objetivo_contexto',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='area_interesse',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='historicoiep',
            name='iev_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='area_curso',
            field=models.CharField(default='NÃ£o informadaNÃ£o informada', max_length=255, verbose_name='Área ou Curso (Foco Estratégico)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competencia',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicoiep',
            name='diagnostic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicoiep',
            name='iep_score',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
                'db_table': 'perfis_alunos',
            },
        ),
        migrations.AlterField(
            model_name='competencia',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='assessments.perfilaluno'),
        ),
        migrations.AlterField(
            model_name='historicoiep',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_iep', to='assessments.perfilaluno'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo', to='assessments.perfilaluno'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
