# Generated by Django 6.1 on 2026-08-20 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_competencia_options_alter_historicoiep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('projeto', 'Projeto'), ('certificado', 'Certificado'), ('artigo', 'Artigo'), ('video', 'Vídeo'), ('outro', 'Outro')], default='projeto', max_length=20)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='assessments.perfilaluno')),
            ],
            options={
                'verbose_name': 'Item de Portfólio',
                'verbose_name_plural': 'Itens de Portfólio',
                'db_table': 'portfolio_itens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='assessments.perfilaluno')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'db_table': 'missoes',
                'ordering': ['status', 'prazo'],
            },
        ),
    ]
