# Generated by Django 5.2.13 on 2026-08-21 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_missao_itemportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='area_relacionada',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='missao',
            name='competencias_desenvolvidas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='missao',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='missao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='assessments.perfilaluno'),
        ),
        migrations.CreateModel(
            name='MissaoAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('progresso', models.PositiveSmallIntegerField(default=0)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='assessments.missao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_aluno', to='assessments.perfilaluno')),
            ],
            options={
                'db_table': 'missoes_aluno',
                'ordering': ['status', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('missao', 'perfil'), name='unique_missao_por_perfil')],
            },
        ),
    ]
