# Generated by Django 5.2.13 on 2026-08-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_seed_missao_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missaoaluno',
            name='motivo_recomendacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missaoaluno',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
