# Generated by Django 5.2.13 on 2026-08-21 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_missaoaluno_motivo_recomendacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='duracao_estimada_minutos',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(240)], verbose_name='Duração estimada (minutos)'),
        ),
        migrations.AddField(
            model_name='missao',
            name='prazo_dias',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Prazo (dias)'),
        ),
        migrations.AddField(
            model_name='missaoaluno',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
