# Generated by Django 5.2.13 on 2026-08-21 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_missao_duracao_estimada_minutos_missao_prazo_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='dias_uteis_estimados',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dias úteis estimados'),
        ),
    ]
