# Generated by Django 5.2.13 on 2026-08-21 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_missao_dias_uteis_estimados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='assessments.perfilaluno')),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_arquivo', models.CharField(max_length=100)),
                ('arquivo_url', models.URLField(max_length=2048)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missao_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='assessments.missaoaluno')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='assessments.portfolio')),
            ],
            options={
                'db_table': 'evidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['perfil', '-updated_at'], name='portfolios_perfil__b931b3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['portfolio', '-created_at'], name='evidencias_portfol_185f64_idx'),
        ),
    ]
