# Generated by Django 5.2.13 on 2026-08-22 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_portfolio_evidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('projeto', 'Projeto'), ('certificado', 'Certificado'), ('imagem', 'Imagem'), ('outro', 'Outro')], max_length=20)),
                ('arquivo_url', models.URLField(max_length=2048)),
                ('arquivo_chave', models.CharField(max_length=512)),
                ('origem', models.CharField(choices=[('missao', 'Missão'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('missao_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_portfolio', to='assessments.missaoaluno')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_portfolio', to='assessments.perfilaluno')),
            ],
            options={
                'db_table': 'evidencias_portfolio',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['perfil', 'ativo', '-criado_em'], name='evidencias__perfil__5c962c_idx'), models.Index(fields=['arquivo_chave'], name='evidencias__arquivo_f415bf_idx')],
            },
        ),
    ]
