# Generated by Django 5.2.13 on 2026-08-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_evidenciaportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoiep',
            name='detalhamento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evidenciaportfolio',
            name='arquivo_chave',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='evidenciaportfolio',
            name='arquivo_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
