# Generated by Django 5.2.13 on 2026-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_historicoiep_detalhamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoiep',
            name='iep_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicoiep',
            name='iev_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
