# Generated by Django 5.2.13 on 2026-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_alter_historicoiep_iep_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missaoaluno',
            name='origem_geracao',
            field=models.CharField(choices=[('regra', 'Regra'), ('regra+ia', 'Regra + IA')], default='regra', max_length=10),
        ),
    ]
