services:
  db:
    image: postgres:16-alpine
    container_name: nova_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME:-nova_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nova_network

  backend:
    build: ./back
    container_name: nova_backend
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-nova_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@nova_db:5432/${DB_NAME:-nova_db}
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nova_network

  frontend:
    build: ./front
    container_name: nova_frontend
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - nova_network

networks:
  nova_network:
    driver: bridge

volumes:
  postgres_data: